[package]
name = "hand-analyze"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
cozad-union-find = "1.1.0"
proc-macro2 = "1.0.103"
quote = "1.0.42"
syn = { version = "2.0.109", feature = ["full"], features = ["full"] }
